export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';
export const SET_SPINNER_MESSAGE = 'SET_SPINNER_MESSAGE';

export const SET_ORDER_DATA = 'SET_ORDER_DATA';
export const REMOVE_ALL_ORDER_DETAIL = 'REMOVE_ALL_ORDER_DETAIL';
export const REMOVE_SELECTED_ORDER = 'REMOVE_SELECTED_ORDER';

export const SET_CATALOG_CATEGORIES = 'SET_CATALOG_CATEGORIES';